# Site settings
title: Yuvasri Loganathan
email: workwithyuvi99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yuvasri's portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
github_username: yuvasri-loganathan

remote_theme: chrisrhymes/bulma-clean-theme
#theme: bulma-clean-theme
livereload: true

# Pagination settings
paginate: 6
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown

#Syntax Highlighter
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-remote-theme

sass:
  style: compressed

collections:
  stories:
    output: true
  products:
    output: true
    layout: product
    show_sidebar: false

exclude: [node_modules, gulpfile.js, vendor, .github]

footer_menu: footer_menu

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: "Yuvasri Loganathan"
      layout: post
      hero_image: /img/blog-hero.jpg
      show_sidebar: true
  - scope:
      path: ""
      type: "stories"
    values:
      author: "Yuvasri Loganathan"
      layout: post
      hero_image: /img/stories.jpg

feed:
  collections:
    - stories
